### ISSUE TITLE
Virtual Notes in queries have dates show up at the top when sorting by descending.

### ISSUE THREAD

**Issue by taylorhadden** [suchnsuch/Tangent#101]
To repro, simply:
1. Create a query for `Notes` – this will include all notes, including virtual ones.
2. Sort the view by date modified, descending. The virtual notes will be sorted to the top.

**Comment by taylorhadden** [comment]
Looks like there is logic here that should be doing this, but it's likely not working as intended. See `sortNodes()` in `Sorting.ts`

**Comment by adamruzicka** [comment]
This seems to be resolved by 64c5a8d7d79a2d438db89ffd844534f3ed45ec47 which went out with 0.8.1.
