### ISSUE TITLE
[BUG] Doesn't support folders with Unicode characters in the name

### ISSUE THREAD

**Issue by blacklightpy** [suchnsuch/Tangent#107]
Those folders don't get recognized.

e.g. emojis in folder name

OS: Windows
Version: 0.8.1

**Comment by taylorhadden** [comment]
This one is fun. When the app is run fully, there is a parsing error. It looks like the emoji codes are being garbled. If I run the same code via a test runner (i.e. outside of the electron context), it runs fine.

Lovely.

**Comment by taylorhadden** [comment]
Updating electron to latest stable seems to have fixed this problem. Perhaps a bug fix within node itself? My local environment was only a few minor revisions off, but I'll take the easy fix.
