### ISSUE TITLE
Unexpected behavior with TODOs when they come after a code block

### ISSUE THREAD

**Issue by spasm** [suchnsuch/Tangent#44]
When TODOs (- [ ]) come after a multi-line code block, they become un-clickable to toggle the state between checked/unchecked.

Version: Tangent 0.7.0-beta.1
OS: macOS 14.4

To reproduce:

1. Create a new note
2. Add a multi-line code block (```)
3. Add 4 new TODOs after the code block

At this point, the first two TODOs don't respond when you click them.  However clicking the third TODO will toggle the first TODO, and clicking the fourth TODO will toggle the second TODO.

Attached is a quick recording showing the behavior

https://github.com/suchnsuch/Tangent/assets/10431596/c77a6250-2ad3-49c8-8582-6b4710e28c48

**Comment by taylorhadden** [comment]
Thanks for the report and the detailed repro steps! I'll check this out.
