### ISSUE TITLE
Shift-click does not select as per standard 

### ISSUE THREAD

**Issue by mediapathic** [suchnsuch/Tangent#54]
(Mac)

In almost every (mac, at least, though to my memory this is also true of windows) app, if the user selects text, then holds shift and clicks elsewhere, the text between the two is selected. In Tangent, the shift modifier seems to be ignored and it reacts as though there was nothing selected initially.

**Comment by taylorhadden** [comment]
Can confirm that I'm seeing this as well. Will have to investigate.

**Comment by mediapathic** [comment]
Confirmed fixed in 0.7.2. Thanks!
