### ISSUE TITLE
Issue with codeblocks rendering

### ISSUE THREAD

**Issue by lorefnon** [suchnsuch/Tangent#56]
I think this is an issue with the latest update. If I enter a triple-backtick to close a codeblock the trailing content's rendering gets messed up in strange ways. Closing  the note and reopening it fixes the rendering.

[Screencast from 2024-04-27 14-31-40.webm](https://github.com/suchnsuch/Tangent/assets/1449492/185aa30a-c488-4bd9-bad4-f14c4347d416)

**Comment by taylorhadden** [comment]
Good bug. This is definitely something that's been an issue in the past.

**Comment by taylorhadden** [comment]
I've not been able to repro this locally. Can you share this file?

**Comment by lorefnon** [comment]
I think this has gotten fixed. After the latest update I can no longer reproduce this.

**Comment by lorefnon** [comment]
Thank you, once again 🙂

**Comment by taylorhadden** [comment]
I'm glad you no longer have this this issue, but I have made no changes in this space! Feel free to reopen this issue if it crops up again :)
