### ISSUE TITLE
Clicking "Manage Rules" does nothing

### ISSUE THREAD

**Issue by adamruzicka** [suchnsuch/Tangent#57]
Steps to reproduce:
1) Click the downward arrow next to "New Note" button
2) Click "Manage Rules"

Actual results:
Nothing happens

Expected results:
I'm taken to Preferences > Creation Rules

Version: 0.7.2
OS: Win10 (19044.4291)

**Comment by taylorhadden** [comment]
Good bug! Been a while since I touched that.

That link should open the "Creation Rules" section of the preference pane.

**Comment by taylorhadden** [comment]
This should be fixed in v0.7.3!
