### ISSUE TITLE
Resizing side bar to full screen creates issues

### ISSUE THREAD

**Issue by Thyverity** [suchnsuch/Tangent#64]
Steps to reproduce:

1. Resize the side bar to full width of the screen.
2. Decrease the window size.

While messing around I discovered that you can make the side bar stretch all the way to the other side of the window, effectively creating a full screen side bar. It became immediately apparent you're not supposed to do that as the tag button gets inconveniently distant and it becomes too hard to downsize it again because of how thin the grabbable area is.
Also if you resize the window itself below the sidebar size, a horizontal scroll bar appears, if you scroll using it the UI elements such as the  close, maximize and minimize buttons are displaced.

https://github.com/suchnsuch/Tangent/assets/168792101/fb0bb921-6010-4899-b708-f67474ce63a1

**Comment by taylorhadden** [comment]
Solid bug. I'll look to smush it.

**Comment by taylorhadden** [comment]
This will be fixed in the next bugfix release!
