### ISSUE TITLE
Limited math rendering on Windows 10

### ISSUE THREAD

**Issue by cosimini** [suchnsuch/Tangent#77]
Inline rendering of mathematics seems to be limited, at least on Windows 10 where I'm using the application. 

In the image attached a comparison between Obsidian and Tangent rendering the same file. As you can see, elements as the sum and integration symbols or parenthesis bigger than one line are not scaled properly.

The two are using two different rendering libraries, MathJaX and KaTeX, but I'm unsure this might be the reason of the difference.
Tested only on Windows 10, I'm unable ATM to test other platforms, version 0.7.6.

![Math_rendering_test](https://github.com/suchnsuch/Tangent/assets/62906444/cdb4e782-3439-4461-9e15-ca11bc4dadcd)

**Comment by taylorhadden** [comment]
Interesting! Given that the layout of individual elements appear to be roughly in the same place, this may be a configuration error on Tangent's part.

Can you provide the source code for this? Seems like a great test case.

**Comment by cosimini** [comment]
That might be the case, before opening the issue I tried to render the same formulas on the [KaTeX website](https://katex.org/) and the outcome is identical to the left side of the image. 

[Math rendering test.md](https://github.com/user-attachments/files/15579718/Math.rendering.test.md)

(Sorry for being unable to make any further tests but I'm not familiar with the language used for this project, neither I'm able to install it on other machines at the moment.)

**Comment by taylorhadden** [comment]
Can confirm, the fonts aren't loading correctly. Time to wrestle with the css…

**Comment by taylorhadden** [comment]
I have a fix for this. Will be coming in v0.8.0-alpha.2

**Comment by taylorhadden** [comment]
Fixed in v0.8.0-alpha.2
