### ISSUE TITLE
Formatting improvements for code block (missing space and hard-to-see cursor in "light mode")

### ISSUE THREAD

**Issue by riwoodward** [suchnsuch/Tangent#82]
I've noticed two minor formatting issues when adding code blocks:

1. Tangent nicely formats a code block with a dark background and rounded edges. On the left-hand side, a few pixels of spacing are added. On the right-hand side, however, the text abruptly ends at the same point as the background. Should there perhaps be similar spacing on the right-hand side? It would look better and make the text easier to read.

An example is the following markdown (I escaped the backslash here so Github formats it correctly in this issue):
```markdown
Content below.

\```
The quick brown fox jumped over the lazy dog. The quick brown fox jumped over the lazy dog
\```

End.
```

which renders as:
![image](https://github.com/suchnsuch/Tangent/assets/8456608/43bad2e2-f38d-4a5e-9e37-72b5ead69544)

2. In light mode, the cursor colour is very dark when editing a code block. This makes it impossible to see the cursor so text editing is difficult. In dark mode, the cursor is visible however. Perhaps the styling could be adjusted so the cursor is more visible when the application is in light mode?

PS, I've just discovered Tangent and it's a fantastic tool. Thanks for introducing this and all your work on it!

**Comment by taylorhadden** [comment]
Thank you!

That lack of space on the right has definitely been something I've been fighting with for a bit now. I agree that it's definitely something that should be there.

The light mode cursor color is a total oversight! I blame it on me never using light mode. That _should_ be easy to fix.
