### ISSUE TITLE
Pressing delete mid-list breaks list

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [suchnsuch/Tangent#90]
@taylorhadden thanks for developing Tangent. Have been testing it on Ubuntu 22.04 and I'm quite impressed and it mostly works really well. 

One issue I've encountered, I have noticed that for numbered lists or checkmark lists, pressing delete in the middle of the list can break the list underneath it. See these images:

Before pressing delete:
![Screenshot from 2024-08-19 15-25-47](https://github.com/user-attachments/assets/aca6db8a-1aa3-42f4-8fad-118ac69c51e2)

After pressing delete: 
![Screenshot from 2024-08-19 15-25-34](https://github.com/user-attachments/assets/7a97c975-27da-442e-8d17-e86b851f9a5b)

**Comment by taylorhadden** [comment]
Thanks for the report! This should hopefully be easy to create a test case for and squash.

**Comment by Kevin-Mattheus-Moerman** [comment]
@taylorhadden it seems to be when there is an empty line, for instance the following, and to then press delete at the 3rd entry: 

```markdown
1. Indentor, force sensor
2. Liner mechanical properties
3. 
4. Meta material
5. Soft robotics
6. LONES
7. Motion capture
8. DIC indentation
```
